#pragma once

#include "CoreMinimal.h"

DECLARE_LOG_CATEGORY_EXTERN(LogEOSCore, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSCombat, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSAbility, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSData, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSStage, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSTelemetry, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSSave, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSUI, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogEOSCharacter, Log, All);
