#include "EchoesOfShinobi.h"

DEFINE_LOG_CATEGORY(LogEOSCore);
DEFINE_LOG_CATEGORY(LogEOSCombat);
DEFINE_LOG_CATEGORY(LogEOSAbility);
DEFINE_LOG_CATEGORY(LogEOSData);
DEFINE_LOG_CATEGORY(LogEOSStage);
DEFINE_LOG_CATEGORY(LogEOSTelemetry);
DEFINE_LOG_CATEGORY(LogEOSSave);
DEFINE_LOG_CATEGORY(LogEOSUI);
DEFINE_LOG_CATEGORY(LogEOSCharacter);

IMPLEMENT_PRIMARY_GAME_MODULE(FDefaultGameModuleImpl, EchoesOfShinobi, "EchoesOfShinobi");
